[package]
name = "sinan_app"
version = "0.1.0-dev"
edition = "2021"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sinan_plugin = { path = "../sinan_plugin", version = "0.1.0-dev" }

bevy_app = "0.10.1"
